### ISSUE TITLE
Improve Bootstrap theme integration

### ISSUE THREAD

**Issue by jongalloway** [dotnet/dotnetfoundation-website#1]
The Bootstrap theme is just linked directly from the _Layout. We're not using multi-instance features in cloudscribe, so perhaps we should just use the standard [bundling and minification](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification) system.

**Comment by joeaudette** [comment]
is there any documentation available for the theme?

running into some issues trying to use bundler minifier to combine the files. 
specifically getting errors about @keyframes and @imports simialr to this issue https://github.com/madskristensen/BundlerMinifier/issues/191

I'm seeing this when I run the task:

Unexpected token, found '{'
Unexpected token, found '"version"'
Expected identifier, found ' '
Expected selector, found '3'
Expected comma or open brace, found '3'
Unexpected token, found '@-webkit-keyframes'
Expected semicolon or closing curly-brace, found '0%'
Unexpected token, found '@keyframes'
Expected semicolon or closing curly-brace, found '0%'
Unexpected token, found '@-webkit-keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@-webkit-keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@-webkit-keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@-webkit-keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@-webkit-keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@-webkit-keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@-webkit-keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@-webkit-keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@-webkit-keyframes'
Expected semicolon or closing curly-brace, found '0%'
Unexpected token, found '@keyframes'
Expected semicolon or closing curly-brace, found '0%'
Unexpected token, found '@import'
Unexpected token, found 'url(//fonts.googleapis.com/css?family=Lato:100,300,400|Open+Sans:400italic,400,600|Muli:300|Indie+Flower:400|Oswald:400,700,300)'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Unexpected token, found '@keyframes'
Expected colon, found '{'
Process terminated with code 0.

Seems like I could move the font urls out separate from the css, but that would still leave some issues with @keyframes which should be valid css but bundler minifier doesn't seem to like it.

Thinking maybe if there is any documentation for the theme it might explain the various parts used

**Comment by joeaudette** [comment]
so far I've integrated the login/logout links and commented out the top nav placeholder items in layout and added them back using navigation.xml and customizing the nav views. So it looks the same but menus are dynamic from the xml file and if you login the admin menu appears.
Will continue tomorrow.

**Comment by joeaudette** [comment]
theme integration is basically done except css minification isn't currently working. Need to either get some upstream help from Mads on the bundler issue or perhaps could try using gulp/grunt instead, though could end up with the same error, not sure.

One thing in the layout I noticed a little section for recent posts in the footer. There is a view component in simplecontent we could use there to pull in the recent posts but would need to customize the view with some logic to extract the first image from each post to use for the thumbnail. Actually I should probably do some work upstream in simplecontent to make it easier to extract the first image from posts there, already have that in the main blog viewmodel, just not in the one for the view component.

As we go through this project if there are things you wish were different or could be improved to make things better in simplecontent let me know, I am certainly open to making upstream changes to improve things.
 
I could take a stab at implementing the recent posts in layout, not sure if it should be a separate issue. I was going to try your blog importer and import posts from the current site but could not find a feed url in the html and not all recent posts have images in them. I guess we would need a default image to fallback to if no image is found in a post. Is there an rss feed url for the current blog? If not I can just make some posts in my local copy to work with.

**Comment by jongalloway** [comment]
I'll mark this one as complete and split up the remaining items into separate issues.
