### ISSUE TITLE
Recent posts in footer

### ISSUE THREAD

**Issue by jongalloway** [dotnet/dotnetfoundation-website#12]
Copied from comment in #1 by @joeaudette 

> One thing in the layout I noticed a little section for recent posts in the footer. There is a view component in simplecontent we could use there to pull in the recent posts but would need to customize the view with some logic to extract the first image from each post to use for the thumbnail. Actually I should probably do some work upstream in simplecontent to make it easier to extract the first image from posts there, already have that in the main blog viewmodel, just not in the one for the view component.
> 
> As we go through this project if there are things you wish were different or could be improved to make things better in simplecontent let me know, I am certainly open to making upstream changes to improve things.
> 
> I could take a stab at implementing the recent posts in layout, not sure if it should be a separate issue. I was going to try your blog importer and import posts from the current site but could not find a feed url in the html and not all recent posts have images in them. I guess we would need a default image to fallback to if no image is found in a post. Is there an rss feed url for the current blog? If not I can just make some posts in my local copy to work with.

**Comment by jongalloway** [comment]
The import RSS feed is `https://dotnetfoundation.org/rss?containerid=3&limit=100` (was not easy to find!)

You have to escape the & feed url, so the import url with feed param is `/blogimport/?feedUrl=https://dotnetfoundation.org/rss?containerid=3%26limit=100`

**Comment by jongalloway** [comment]
I've been thinking about this too because I feature more recent posts on the home page. It's a little tougher because some posts have images, some don't. I've got an idea for an SVG based thumbnail using the headline text but for now we should just use a default image. I think I'd like to try it out this weekend first.

**Comment by joeaudette** [comment]
sounds good, on my end I will do a little upstream work in simplecontent to make it easy to extract the first image in a post for the recent posts view component. Even if we end up using an svg thing for this project it will come in handy for other projects

**Comment by joeaudette** [comment]
I have implemented the recent posts in the footer, but made it so that if no posts exist it still shows the boilerplate fake posts from the theme.
changes pushed to master
