### ISSUE TITLE
solution structure and repo structure

### ISSUE THREAD

**Issue by joeaudette** [dotnet/dotnetfoundation-website#2]
I would like to reorganize the solution with your permission, but realize it would also break the CI you have setup so won't do it unless you approve.

Issues as I see them:

1. When I cloned the repo it seems the web app is directly in the src folder and the .sln file is also in the same folder with .csproj. I would like to rename the src folder as webapp or something like that and then move the .sln file to the root. That would be better if we decide to add other projects to the solution, but if you only want to add code directly in the main web app I guess we could leave things as they are. I don't think we need an src folder, that was the way things were setup with the 1.x vs project templates but the new project templates don't do that so I didn't do that with the 2.0 starter kits. It can be good to use an src folder if there will also be unit tests in the future so they can be moved to a tests folder separate from src, so happy to go with whatever you decide but probably good to decide early on so history doesn't get messed up by a folder reorg. So I propose either rename src as WebApp or move the web app into a sub folder WebApp below src and move .sln to the root folder

2. I would like to delete the dp_keys folder from the repo and then gitignore that folder since data protection keys should not be public. Actually will need to change and not use keys from there but for production I think azure key vault is where the data protection keys are supposed to go, I will research that. Not sure if you are planning to let public users login to the site with social auth, but the data protection keys are also used to encrypt the secrets for social auth in the db as well as the smtp password. If we get to a point of syncing dbcontent from production to dev or vice versa thenthe keys won't be the same so the settings would have to be fixed using the local keys after any kind of data sync like that.

**Comment by jongalloway** [comment]
1. I'd like to keep source out of the root and use that for repo markdown content and other project related files. I like to use `git mv` to move files and directories to keep history. Let's go with /src/WebApp so we can also use /src/Test, possible Azure Functions project, etc. I'm happy to fix the App Service deployment when it's moved over.
1. Okay to delete dp_keys, gitignore, etc.

**Comment by joeaudette** [comment]
sounds good to me! I did not know about git mv command so learned something new today already! I will let you do that though at your own schedule since you will want to coordinate it with changes to your CI. I will just get started on other issues with the current structure.

**Comment by joeaudette** [comment]
just an update on data protection keys. Kind of surprised to find that [in order to have the same keys used across azure deployment slots](http://blog.stoverud.no/posts/asp-net-core-dataprotection-and-azure-web-apps/) we need to use [Blob storage as per the docs](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers). I guess that is secure since the docs say to do it that way but had assumed there would be some easy way to use azure key vault which I thought was exactly for that purpose.

**Comment by jongalloway** [comment]
Closing this since base issue is fixed
