### ISSUE TITLE
"Learn how to submit your project." is not a link

### ISSUE THREAD

**Issue by mstum** [dotnet/dotnetfoundation-website#47]
http://www.dotnetfoundation.org/Projects

*Of course, we’re always on the lookout for new open-source projects to support. **Learn how to submit your project.***

I assume the "Learn how to submit your project" should be linked to something?

![image](https://user-images.githubusercontent.com/104127/45527642-b55e9c80-b7aa-11e8-809d-8409f2c3ff0f.png)

**Comment by zwcloud** [comment]
#69 will add the correct link: https://github.com/dotnet/foundation/blob/master/guidance/new-projects.md

**Comment by jongalloway** [comment]
Fixed by #69
