### ISSUE TITLE
Upcoming Events and Meetups appear to display be old

### ISSUE THREAD

**Issue by andrewcahill** [dotnet/dotnetfoundation-website#55]
On home page under the ‘Upcoming Events and Meetups’ blog the events and meetups appear to show already passed events/days - may need to update the “from time”

**Comment by jongalloway** [comment]
Thanks, this was fixed by a815812

Turns out caching for 18000 hours is a bit too long...

**Comment by andrewcahill** [comment]
Ahh, cool.

Yeah it might be by a little  :)
