### ISSUE TITLE
Projects Search is not working

### ISSUE THREAD

**Issue by Omarkth** [dotnet/dotnetfoundation-website#63]
I'm getting the same list of projects no matter what I search for..

**Comment by SeanKilleen** [comment]
@Omarkth I tried to repro this but couldn't. What search query are you running, and what browser are you on?

My repro steps:

* Visit projects page: https://dotnetfoundation.org/projects
* Type `Cecil` into the search box
* Hit enter

Expected result: See only the Cecil project
Actual result: See only the Cecil project ✅

**Comment by svick** [comment]
@SeanKilleen It seems to be fixed. It didn't work for me yesterday, but it works today.

**Comment by Omarkth** [comment]
Yes, it seems to be fixed. It wasn't working when I reported it.
