### ISSUE TITLE
Broken image on cla.dotnetfoundation.org

### ISSUE THREAD

**Issue by ghost** [dotnet/dotnetfoundation-website#82]
The header on <https://cla.dotnetfoundation.org> tries to source [/images/logo_big.png](https://www.dotnetfoundation.org/images/logo_big.png) from www, but that's a 404.

Steps to reproduce:

1. Visit <https://cla.dotnetfoundation.org/>
2. Look at the header

Results:

Browser shows broken image placeholder.

**Comment by jongalloway** [comment]
This has been fixed in the latest CLA update
